### ISSUE TITLE
Dynamic override / adding of properties for API ML core components from extensions

### ISSUE THREAD

**Issue by pablocarle** [zowe/community#1719]
Proposal for adding properties in manifest.yaml for extensions: 

```yml
apimlServices:
  propertyOverrides:
    - apiml.saf.security.provider: ccsIdt
```
This could be included in the extension loading mechanism in API ML (Gateway / Discovery)
